### ISSUE TITLE
Option to not re-define non-configurable properties

### ISSUE THREAD

**Issue by dougwilson** [component/merge-descriptors#1]
It would be nice to have the option (or maybe just always work this way) to not try and merge into non-configurable properties. For example, I want an option for this to silently not error:
```js
var a = {}
var b = {}

Object.defineProperty(a, 'foo', {value: 'buzz'})
b.foo = 'bar'

merge(a, b)
```

**Comment by dougwilson** [comment]
Sorry, the code I originally had the order wrong; I updated the original post with the correct code.

**Comment by jonathanong** [comment]
added :P

**Comment by jonathanong** [comment]
btw if you accept this invitation, coveralls will take you like 5 minutes to login hahaha

**Comment by dougwilson** [comment]
lol.

**Comment by dougwilson** [comment]
@jonathanong which API do you like better?
```js
// Simplistic
merge(a, b, true)
```

```js
// Extendable
merge(a, b, { overrideConfigurables: false })
```

**Comment by jonathanong** [comment]
Simplistic! If we need to add more options, might as well make a new module

**Comment by dougwilson** [comment]
Should I just publish this as 1.0.0?

**Comment by dougwilson** [comment]
P.S. I don't know how to publish to component

**Comment by jonathanong** [comment]
It uses git tags, so if you create a tag it should be fine

**Comment by jonathanong** [comment]
1.0.0 is fine to me

**Comment by dougwilson** [comment]
Gotcha, I just wasn't familiar :) Please check out the commit and let me know if it's good or not.
