### ISSUE TITLE
SSR issue

### ISSUE THREAD

**Issue by impulsenok** [component/merge-descriptors#13]
When i'm trying to build SSR(Angular + ngUniversal), SSR serve is failing with:
<Cannot read property 'getOwnPropertyNames' of undefined.>
It is caused by 
<`Object.getOwnPropertyNames(src).forEach(function forEachOwnPropertyName(name)...`> line.
Why <Object> is undefined there?
At the very beginning of the file there is line <`var hasOwnProperty = Object.prototype.hasOwnProperty`>, and Object is available there...

**Comment by dougwilson** [comment]
Please provide step by step instructions for how to reproduce the issue.

**Comment by impulsenok** [comment]
Third party library internal issue.
