### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by amir-khoshbakht** [component/merge-descriptors#16]
This line is misspelled in the node_modules file
```node_modules\merge-descriptors\index.js```
https://github.com/component/merge-descriptors/blob/dec51af1c9e3c1ee30e2258d7de9f676f5d30771/index.js#L50C15-L50C25

**Comment by dougwilson** [comment]
It is unclear how that is misspelled. The javascript api is `Object.getOwnPropertyDescriptor` and it is spell the same way in the comment you pointed to.
