### ISSUE TITLE
Needs tests

### ISSUE THREAD

**Issue by dougwilson** [component/merge-descriptors#2]

**Comment by grabbou** [comment]
hey, do you need some help? Can submit few test-cases + add travis builds so we can check every next PR that's being merged :)

**Comment by dougwilson** [comment]
That would be a great help, yes please!

**Comment by grabbou** [comment]
Cool! I am in a process of writing a Medium post about `Express under the hood` and accidentally arrived here by exploring some deps in the application.js. It's actually quite surprising how many small modules yet completely forgotten are there!

**Comment by dougwilson** [comment]
Ah, I see. I would like to read that when you're eventually done , so feel free to email me a link :D

**Comment by grabbou** [comment]
Ha! Will find you on Gitter somehow later on :)

**Comment by grabbou** [comment]
Submitted my proposed test cases, what you think? Once we are done with it, we can add code coverage reporters + a badge :)
