### ISSUE TITLE
`Object.getOwnProeprtyDescriptor` is showing a lot of deprecation warnings in chrome

### ISSUE THREAD

**Issue by gkatsev** [component/merge-descriptors#5]
![](https://cldup.com/FUj72ZuM40.png)
This line specifically: https://github.com/component/merge-descriptors/blob/master/index.js#L52
It should probably check for those and not get those at that point.

**Comment by dougwilson** [comment]
What the heck object are you trying to clone? Hopefully you are not trying to clone a window object.

We definitely cannot put in a blacklist of property names, because it would break older browsers where those are not deprecated and are necessary.

Any proposed solution?

**Comment by gkatsev** [comment]
I am using proxyquireify to mock out [`global/window`](https://github.com/Raynos/global/blob/master/window.js) in a module. So, I guess I am cloning `window`? The usage is in the linked PR videojs/video.js#2633

**Comment by gkatsev** [comment]
I do not currently have a proposed solution other than maybe do UA switching for when to blacklist those. But that's really ugly.

**Comment by dougwilson** [comment]
Gotcha. Unfortunately I have no experience on the front end and will have to rely on you or someone else to propose a fix or PR, if there is a desire to D something regarding the warnings getting printed on the console (which is not harmful, just annoying).

**Comment by gkatsev** [comment]
Yeah, definitely not harmful. I'll have to think about it some more to see if I can think of a better way of fixing this.

**Comment by dougwilson** [comment]
Hi @gkatsev , I'm going to close this issue for now, since I don't think any progress has been made. I skimmed around the C++ source for Chromium to see if there was a way to tell from JavaScript-land if a property was deprecated and not try to get the property descriptor for that property, but it doesn't seem to have any way.

**Comment by gkatsev** [comment]
Sounds good to me. Thanks @dougwilson. I may even just remove this test because it isn't useful enough to worry about this weirdness. However, if I do come up with a good solution, I'll definitely ping you.

Also, I wanted to say thanks for all your hard work on everything you maintain @dougwilson!
